# Generated by Django 3.0.4 on 2020-03-10 01:58

from django.db import migrations
from django.conf import settings


def seed(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    User.objects.create_user(
        username="jnlsinger",
        password="test"
    )

    user = User.objects.get(username="jnlsinger")

    Post = apps.get_model('catspotting_backend', 'Post')
    Comment = apps.get_model('catspotting_backend', 'Comment')
    post1 = Post(owner='user', location='Austin, TX',
                 body='GASP', img_url='https://i.imgur.com/zGs25jd.jpg')
    post2 = Post(owner='user', location='Austin, TX',
                 body="A friend", img_url='https://i.imgur.com/YdqnfbW.jpg')
    post3 = Post(owner='user', location='Austin, TX',
                 body='Wot a lad', img_url='https://i.imgur.com/8pJW7zd.jpg')
    post4 = Post(owner='user', location='Austin, TX',
                 body='LOOK AT HIMB', img_url='https://i.imgur.com/BQAQb8y.jpg')
    post5 = Post(owner='user', location='Austin, TX',
                 body='Show off', img_url='https://i.imgur.com/iSmtynw.jpg')
    post6 = Post(owner='user', location='Austin, TX',
                 body='He loves pats', img_url='https://i.imgur.com/8wucYp8.jpg')
    post7 = Post(owner='user', location='Austin, TX',
                 body='Mischievous', img_url='https://i.imgur.com/eM7uOe7.jpg')
    post8 = Post(owner='user', location='Austin, TX',
                 body='Mah heart', img_url='https://i.imgur.com/NDlPNY0.jpg')
    post9 = Post(owner='user', location='Austin, TX',
                 body='Dorty', img_url='https://i.imgur.com/4PzrJ9h.jpg')

    post1.save()
    post2.save()
    post3.save()
    post4.save()
    post5.save()
    post6.save()
    post7.save()
    post8.save()
    post9.save()

    Comment(post=post1, owner='DocTree', body='WHOA').save()
    Comment(post=post2, owner='DocTree', body='Absolute budy').save()
    Comment(post=post3, owner='DocTree', body='A fine specimen').save()
    Comment(post=post4, owner='DocTree', body='Who is he').save()
    Comment(post=post5, owner='DocTree', body='Love that Tuxy boi').save()
    Comment(post=post6, owner='DocTree', body='TUX').save()
    Comment(post=post7, owner='DocTree', body='I\'m love').save()
    Comment(post=post8, owner='DocTree', body='HUG').save()
    Comment(post=post9, owner='DocTree', body='He love dirt').save()


def fallow(apps, schema_editor):
    Post = apps.get_model('catspotting_backend', 'Post')
    Comment = apps.get_model('catspotting_backend', 'Comment')
    Post.objects.all().delete()
    Fad.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catspotting_backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
