# Generated by Django 3.0.4 on 2020-03-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catspotting_backend', '0002_auto_20200306_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=180),
        ),
    ]
